---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../operator/gitops/argocd/pipeline-service

patches:
  - path: tekton-results/minio-create-bucket.yaml
  - path: tekton-results/minio-tls.yaml
  - path: tekton-results/postgres.yaml

  # Skip applying the Tekton operands while the Tekton operator is being installed.
  # See more information about this option, here:
  # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
