---
check: []
compact: false
evaluate-variables: true
framework:
  - kubernetes
  - dockerfile
  - github_actions
  - kustomize
skip-download: false
output: cli
quiet: true
skip-check:
  # skip Healthcheck instruction error for Docker Images
  - CKV_DOCKER_2
  # not enforcing liveness/readiness probes at this time; minimally, chains, results, metric exporter do not have
  # we have opened https://github.com/tektoncd/results/issues/280 upstream
  - CKV_K8S_8
  - CKV_K8S_9
  # RHTAP utilizes LimitRanges for cpu/mem requests and limits settings (handles 10-13)
  - CKV_K8S_10
  - CKV_K8S_11
  - CKV_K8S_12
  - CKV_K8S_13
  # image ref related
  - CKV_K8S_43 # deployments referenced by checkov are either items like chains which will be replace by openshift-pipelines 1.10 or a fooled by our use of kustomize for image setting
  - CKV_K8S_14 # deployments referenced by checkov are either items like chains which will be replace by openshift-pipelines 1.10 or a fooled by our use of kustomize for image setting
  - CKV_K8S_15 # with sha specific image refs setting pull policy to always is redundant and negates us of openshift node cache
  # need to reivew chains/pac needs to read secrets in a couple of namespaces, not a clusterrolebinding, create webhooks
  - CKV2_K8S_5
  # there is no use of hostPID, hostIPC, hostNetwork in repo, but scan complains about not setting explicitly to false
  # will check in live tests
  - CKV_K8S_17
  - CKV_K8S_18
  - CKV_K8S_19
  # openshift scc / security addresses these check by mutating pod under the covers
  # with pods getting assigned the restricted scc unless explicitly allowed otherwise
  - CKV_K8S_20 # no allowPrivilegeEscalation
  - CKV_K8S_21 # the default namespace should not be used
  - CKV_K8S_22 # read only FS
  - CKV_K8S_23 # admission of root containers
  - CKV_K8S_25 # we are not adding capabilities, running under restricted-scc
  - CKV_K8S_28 # admission of NET RAW capability
  - CKV_K8S_29 # apply security context to pod and containers
  - CKV_K8S_30 # apply security context to containers
  - CKV_K8S_31 # runtime/default seccomp profile
  - CKV_K8S_33 # also, no kubernetes-dashboard on openshift
  - CKV_K8S_37 # any capabilities
  - CKV_K8S_38 # our pods almost always a) need to access api svr, b) do not have privileged SA
  - CKV_K8S_40 # high UID number
  - CKV_K8S_35 # opened https://github.com/tektoncd/results/issues/432 for secrets via env var
  # need to allow argocd to create/delete the validatingadmissionwebhooks for tekton (core part of knative)
  - CKV_K8S_155
  - CKV_K8S_157
  - CKV2_K8S_6 # use NetworkPolicy like what registration-service and integration-service employ are untenable for tekton controllers
soft-fail: false
skip-path:
  - developer
  - ci
