apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipelines-in-a-pod
  name: cpipelines
  namespace: cpipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelines-in-a-pod
  template:
    metadata:
      labels:
        app: pipelines-in-a-pod
    spec:
      containers:
        - image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.32.0
          name: cpipelines
          args:
            - -kubeconfig-writer-image
            - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.32.0
            - -git-image
            - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.32.0
            - -entrypoint-image
            - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.32.0
            - -nop-image
            - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.32.0
            - -imagedigest-exporter-image
            - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.32.0
            - -pr-image
            - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.32.0
            - -gsutil-image
            - gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:27b2c22bf259d9bc1a291e99c63791ba0c27a04d2db0a43241ba0f1f20f4067f
            - -shell-image
            - registry.access.redhat.com/ubi8/ubi-minimal@sha256:54ef2173bba7384dc7609e8affbae1c36f8a3ec137cacc0866116d65dd4b9afe
            - -shell-image-win
            - mcr.microsoft.com/powershell:nanoserver@sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6
          env:
            - name: KUBECONFIG
              value: /workspace/kubeconfig/admin.kubeconfig
            - name: METRICS_DOMAIN
              value: knative.dev/some-repository
            - name: SYSTEM_NAMESPACE
              value: tekton-pipelines
          volumeMounts:
            - mountPath: /workspace/kubeconfig/admin.kubeconfig
              name: kubeconfig
              subPath: admin.kubeconfig
      volumes:
        - name: kubeconfig
          configMap:
            name: ckcp-kubeconfig