apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gitops-repo
  namespace: ci-runner
spec:
  url: "https://gitops.com/group/project"
  git_provider:
    secret:
      name: "gitops-webhook-config"
      # Set this if you have a different key in your secret
      # key: "provider.token"
    webhook_secret:
      name: "gitops-webhook-config"
      # Set this if you have a different key in your secret
      # key: "webhook.secret"

