---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chains-config
  namespace: openshift-pipelines

data:
  # See https://tekton.dev/docs/chains/config/

  # Configure TaskRun attestation. RHTAP does not leverage the TaskRun
  # attestations. This tells Tekton Chains to not store them in the OCI
  # registry.
  artifacts.taskrun.format: "in-toto"
  artifacts.taskrun.storage: ""

  # Configure PipelineRun attestation
  artifacts.pipelinerun.format: "in-toto"
  artifacts.pipelinerun.storage: "oci"

  # Configure image signing
  artifacts.oci.storage: "oci"

  # Rekor integration is disabled for now. It is planned to be re-introduced
  # in the future.
  transparency.enabled: "false"
