---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-cluster
spec:
  params:
    - name: ocp_version
      description: ocp cluster version that you want to provision
      default: "4.14.3"
    - name: region
      description: ocp cluster region where you want to provision
      default: "us-east-1"
    - name: cluster-name
    - name: target_branch
  workspaces:
    - name: workdir
  steps:
    - name: install-cluster
      image: quay.io/redhat-pipeline-service/ci-runner:$(params.target_branch)
      imagePullPolicy: Always
      env:
        - name: CLUSTER_NAME
          value: "$(params.cluster-name)"
        - name: KUBECONFIG_DIR
          value: "$(workspaces.workdir.path)/.kube"
        - name: REGION
          value: "$(params.region)"
        - name: OCP_VERSION
          value: "$(params.ocp_version)"
        - name: ROSA_TOKEN
          valueFrom:
            secretKeyRef:
              name: plnsvc-ci-secret
              key: "PLNSVC_ROSA_TOKEN"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: plnsvc-ci-secret
              key: "PLNSVC_AWS_KEY_ID"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: plnsvc-ci-secret
              key: "PLNSVC_AWS_KEY"
      workingDir: "$(workspaces.workdir.path)/source"
      command:
        - ci/images/ci-runner/hack/bin/deploy-cluster.sh
