---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: destroy-cluster
spec:
  params:
    - name: cluster-name
    - name: region
      description: ocp cluster region where you want to provision
    - name: target_branch
  workspaces:
    - name: source
    - name: output
  steps:
    - name: destroy
      image: quay.io/redhat-pipeline-service/ci-runner:$(params.target_branch)
      env:
        - name: CLUSTER_NAME
          value: "$(params.cluster-name)"
        - name: ROSA_TOKEN
          valueFrom:
            secretKeyRef:
              name: plnsvc-ci-secret
              key: "PLNSVC_ROSA_TOKEN"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: plnsvc-ci-secret
              key: "PLNSVC_AWS_KEY_ID"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: plnsvc-ci-secret
              key: "PLNSVC_AWS_KEY"
        - name: KUBECONFIG_DIR
          value: "$(workspaces.output.path)"
        - name: REGION
          value: "$(params.region)"
      workingDir: "$(workspaces.source.path)"
      command:
        - $(workspaces.source.path)/ci/images/ci-runner/hack/bin/destroy-cluster.sh
