---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: destroy-cluster
spec:
  params:
    - name: cluster-name
    - name: region
      description: ocp cluster region where you want to provision
    - name: target_branch
  workspaces:
    - name: source
    - name: output
  steps:
    - name: destroy
      image: quay.io/redhat-pipeline-service/ci-runner:$(params.target_branch)
      env:
        - name: CLUSTER_NAME
          value: "$(params.cluster-name)"
        - name: BW_CLIENTID
          valueFrom:
            secretKeyRef:
              name: hypershift-bitwarden
              key: "BW_CLIENTID"
        - name: BW_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: hypershift-bitwarden
              key: "BW_CLIENTSECRET"
        - name: BW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hypershift-bitwarden
              key: "BW_PASSWORD"
        - name: KUBECONFIG_DIR
          value: "$(workspaces.output.path)"
        - name: REGION
          value: "$(params.region)"
      workingDir: "$(workspaces.source.path)"
      command:
        - $(workspaces.source.path)/ci/images/ci-runner/hack/bin/destroy-cluster.sh
