---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pipeline-service-setup
spec:
  params:
    - name: repo_url
    - name: revision
    - name: target_branch
  workspaces:
    - name: kubeconfig-dir
      description: The kubeconfig of new cluster will be stored onto the volume backing this Workspace
    - name: source
  steps:
    - name: run-plnsvc-setup
      image: quay.io/redhat-pipeline-service/ci-runner:$(params.target_branch)
      resources:
        requests:
          memory: 500Mi
          cpu: 300m
      workingDir: "$(workspaces.source.path)"
      env:
        - name: KUBECONFIG
          value: "$(workspaces.kubeconfig-dir.path)/kubeconfig"
        - name: REPO_URL
          value: $(params.repo_url)
        - name: REPO_REVISION
          value: $(params.revision)
      command:
        - ci/images/ci-runner/hack/bin/run-plnsvc-setup.sh
