resources:
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/300-clusterinterceptor.yaml
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/300-clustertriggerbinding.yaml
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/300-eventlistener.yaml
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/300-trigger.yaml
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/300-triggerbinding.yaml
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/300-triggertemplate.yaml
  #config files
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/config-defaults-triggers.yaml
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/config-feature-flags.yaml
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/config-info.yaml
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/config-logging.yaml
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/config-observability.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization