apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    app.kubernetes.io/part-of: tekton-results
    app.kubernetes.io/version: v0.3.0
  name: postgres-service
  namespace: openshift-pipelines
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    app: postgres
    app.kubernetes.io/part-of: tekton-results
    app.kubernetes.io/version: v0.3.0
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: tekton-results
    app.kubernetes.io/version: v0.3.0
  name: tekton-results-api-service
  namespace: openshift-pipelines
spec:
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    - name: prometheus
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tekton-results-api
    app.kubernetes.io/part-of: tekton-results
    app.kubernetes.io/version: v0.3.0
