---
name: Build and Publish access-setup Image
on:
  push:
    branches:
      - main
    paths:
      - "images/access-setup/**"
  workflow_dispatch:
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v3
      - name: Get the short sha
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -b -7)"
      # Build and push a kcp-registrar image, tagged with latest and the commit SHA.
      - name: Build access-setup Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: access-setup
          context: ./images/access-setup
          tags: latest ${{ steps.vars.outputs.sha_short }} ${{ github.ref_name }}
          containerfiles: |
            ./images/access-setup/Dockerfile
          build-args: |
            KCP_BRANCH=release-0.7
      - name: Push to quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }} ${{ github.ref_name }}
          registry: quay.io/redhat-pipeline-service
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
