---
name: Upgrade kcp
on:
  # Runs every Sunday at 00:00:00
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  kcp-upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Check if a new kcp version exists and update the files if it does
        id: fetch-kcp-version
        run: |
          ./images/kcp-upgrade/upgrade.sh
          echo "::set-output name=NEW_KCP_VERSION_FOUND::$?"

      - name: Create PR if a new kcp version exists
        id: create-pull-request
        uses: peter-evans/create-pull-request@v4
        if: ${{ steps.fetch-kcp-version.outputs.NEW_KCP_VERSION_FOUND }} == 0
        run: |
          echo "::set-output name=NEW_KCP_VERSION::$(curl -s https://api.github.com/repos/kcp-dev/kcp/releases/latest | yq '.tag_name' | sed 's/v//')"
        with:
          token: ${{ secrets.UPGRADE_TOKEN }}
          commit-message: 'Upgrade kcp to the latest available version: ${{ steps.fetch-kcp-version.outputs.NEW_KCP_VERSION }}'
          branch: upgrade_kcp
          delete-branch: true
          title: 'Upgrade kcp to the latest version: ${{ steps.fetch-kcp-version.outputs.NEW_KCP_VERSION }}'
