name: Execute local test

on:
  push:
    branches:
      - main

jobs:
  e2e-shared-server:
    name: e2e-shared-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: v1.17

      - uses: actions/checkout@v3
        with:
          repository: kcp-dev/kcp
          ref: release-0.6
      - name: Build KCP plugin
        run: |-
          go mod vendor
          make install
          kubectl-kcp --version
      # Install kind with a local registry
      - uses: container-tools/kind-action@v1
        name: Kubernetes KinD Cluster w/local registry

      - uses: actions/checkout@v3
      - name: Test local setup
        run: |-
          ./local/kind/setup.sh

      - run: |-
          ./local/kcp/start.sh